# Generated by Django 4.1 on 2023-07-18 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homePage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videos'),
        ),
    ]
